---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ametrine/public_html/
    - /bin/rm -rf $DEPLOYPATH/assets
    - npm ci
    - npm run build
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/. $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/cp -R api/. $DEPLOYPATH/api/
